### ISSUE TITLE
.SelectColumns might not be optional

### ISSUE THREAD

**Issue by keltia** [maxim2266/csvplus#1]
I'm loading a csv file with 38 fields.  Until I selected a few interesting columns with .SelectColumns(), all the rows were correctly read but all rows were empty.  The csv file does have field names in the first row.

See https://gist.github.com/keltia/f1dcb745fdef27d5fb2da76b17c9c124 for code extract.  The repo is not public because it contains personal test data I can not show.

First line of the csv is the following:

`EmailAddress;PSComputerName;RunspaceId;FirstSyncTime;LastPolicyUpdateTime;LastSyncAttemptTime;LastSuccessSync;DeviceType;DeviceID;DeviceUserAgent;DeviceWipeSentTime;DeviceWipeRequestTime;DeviceWipeAckTime;LastPingHeartbeat;RecoveryPassword;DeviceModel;DeviceImei;DeviceFriendlyName;DeviceOS;DeviceOSLanguage;DevicePhoneNumber;MailboxLogReport;DeviceEnableOutboundSMS;DeviceMobileOperator;Identity;Guid;IsRemoteWipeSupported;Status;StatusNote;DeviceAccessState;DeviceAccessStateReason;DeviceAccessControlRule;DevicePolicyApplied;DevicePolicyApplicationStatus;LastDeviceWipeRequestor;DeviceActiveSyncVersion;NumberOfFoldersSynced;SyncStateUpgradeTime`

**Comment by maxim2266** [comment]
Yes, that was a bug. I have fixed it with the commit earlier today. Now, given the file of
```
EmailAddress;PSComputerName;RunspaceId;FirstSyncTime
aaa@zzz.com;xyz-1;123;17/10/2017
bbb@zzz.com;xyz-2;456;16/10/2017
ccc@zzz.com;xyz-3;789;15/10/2017
ddd@zzz.com;xyz-4;999;14/10/2017
```
the following code
```go
func main() {
	src := csvplus.FromFile("issue.csv").Delimiter(';')
	rows, err := csvplus.Take(src).ToRows()

	if err != nil {
		die(err.Error())
	}

	for _, row := range rows {
		fmt.Printf("%v\n", row)
	}
}

func die(msg string) {
	os.Stderr.WriteString("ERROR: " + msg + "\n")
	os.Exit(1)
}
```
produces the output:
```
{ "EmailAddress" : "aaa@zzz.com", "FirstSyncTime" : "17/10/2017", "PSComputerName" : "xyz-1", "RunspaceId" : "123" }
{ "EmailAddress" : "bbb@zzz.com", "FirstSyncTime" : "16/10/2017", "PSComputerName" : "xyz-2", "RunspaceId" : "456" }
{ "EmailAddress" : "ccc@zzz.com", "FirstSyncTime" : "15/10/2017", "PSComputerName" : "xyz-3", "RunspaceId" : "789" }
{ "EmailAddress" : "ddd@zzz.com", "FirstSyncTime" : "14/10/2017", "PSComputerName" : "xyz-4", "RunspaceId" : "999" }
```
I believe that should fix the problem you described, please let me know if it doesn't.

**Comment by keltia** [comment]
You may have broken the other case :)

```
848 [22:26] roberto@lonrach:keltia/erc-eas> ./erc-eas -D ~/Dropbox/Sync/EEC/CSS/Mobiles/EAS-full-20171009.csv
erc-eas EAS Interactive Shell v0.4.0
2017/10/17 22:26:43 error loading /Users/roberto/Dropbox/Sync/EEC/CSS/Mobiles/EAS-full-20171009.csv: Data source "/Users/roberto/Dropbox/Sync/EEC/CSS/Mobiles/EAS-full-20171009.csv", row 0: Column not found: EmailAddress
2017/10/17 22:26:43 error loading /Users/roberto/Dropbox/Sync/EEC/CSS/Mobiles/EAS-full-20171009.csv: Data source "/Users/roberto/Dropbox/Sync/EEC/CSS/Mobiles/EAS-full-20171009.csv", row 0: Column not found: EmailAddress
```

with the same code:
```
	allLines := csvplus.FromFile(fn).Delimiter(';').NumFields(38).SelectColumns(fields...)
	rows, err := csvplus.Take(allLines).ToRows()
	if err != nil {
		log.Printf("error loading %s: %v", fn, err)
		return
	}
```

**Comment by maxim2266** [comment]
Just using the example from my previous message, if I replace the line where the source is defined with the code:
```Go
src := csvplus.FromFile("issue.csv").Delimiter(';').NumFields(4).SelectColumns("PSComputerName", "RunspaceId")
```
the output will be:
```
{ "PSComputerName" : "xyz-1", "RunspaceId" : "123" }
{ "PSComputerName" : "xyz-2", "RunspaceId" : "456" }
{ "PSComputerName" : "xyz-3", "RunspaceId" : "789" }
{ "PSComputerName" : "xyz-4", "RunspaceId" : "999" }
```
but if I replace the first column name in the call to `SelectColumns` with `ZZZ`, I will get the following error:
```
ERROR: Data source "issue.csv", row 0: Column not found: ZZZ
```

Are you sure the column `EmailAddress` is really present in the `.csv` file you are processing?

**Comment by keltia** [comment]
Found the issue.  The input file has a BOM (which is useless in UTF-8) and that was messing up the 1st field which is… "EmailAddress".

So it is fixed, sorry :)

**Comment by maxim2266** [comment]
No problem. :)
