### ISSUE TITLE
UTF-8 + BOM: do you handle this?

### ISSUE THREAD

**Issue by keltia** [maxim2266/csvplus#2]
I have a few csv files coming from a WIndows-based system and it generates them as UTF-8 + BOM.  It seems that either `encoding/csv` or `csvplus` fails to handle this and the first field will be see as` \uFEFF<the field>`.

```
"\ufeffEmailAddress":"foo.bar@example.com"
```
It used to work before I switched to `csvplus`.

Thanks.

**Comment by maxim2266** [comment]
The actual reading is done using `csv.Reader` from `encoding/csv` package, and the only interface `csvplus` provides is the `FromFile` constructor. The relevant chunk of code is this:
```Go
	file, err := os.Open(s.name)

	if err != nil {
		return s.mapError(err, lineNo)
	}

	defer file.Close()

	// csv.Reader
	reader := csv.NewReader(file)
	reader.Comma = s.delimiter
	reader.Comment = s.comment
	reader.LazyQuotes = s.lazyQuotes
	reader.TrimLeadingSpace = s.trimLeadingSpace
	reader.FieldsPerRecord = s.numFields
```
In your case, did you have any special code to handle the BOM?

**Comment by keltia** [comment]
No but I seem to recall I dropped the first line upon reading which worked around that.

**Comment by maxim2266** [comment]
Here you can probably achieve the same functionality using [AssumeHeader](https://godoc.org/github.com/maxim2266/csvplus#File.AssumeHeader) and dropping the first line.
