### ISSUE TITLE
How would I write output to csv for all headers irrespective of header names?

### ISSUE THREAD

**Issue by sujit-baniya** [maxim2266/csvplus#6]
Currently, I've to define column names to be able to output to file. Instead is there any option to include all columns?

```
ToCsvFile("out.csv", "phone", "country_code", "phone_type", "carrier", "region")
```

**Comment by maxim2266** [comment]
Each row is implemented as Go `map[string]string`, and there is no definite order of the values if you just enumerate them in a loop. Also, the order may be different on each invocation of such a loop due to how the map is implemented in Go, making your output will essentially meaningless. Supplying a list of column names guarantees the correct order of values.

**Comment by itsursujit** [comment]
True.
It would be better if this library has following functions. It would be easier to use
1) FileHeader
For e.g.  
`csvplus.FromFile("sample.csv").FileHeader` Would give Header Row

2) FileRowCount
For e.g.
`csvplus.FromFile("sample.csv").FileRowCount` Would give total Rows Count.

3) DataHeader
For e.g.  
`csvplus.FromFile("sample.csv").Map(...).DataHeader` Would give DataSource Header Row

4) DataRowCount
For e.g.
`csvplus.FromFile("sample.csv").Map(...).FileRowCount` Would give total Rows Count after the map.

Also some helpful functions like:

5) Distinct(column names)
For e.g.
`csvplus.FromFile("sample.csv").Distinct()` Would remove duplicates. No need to use IndexOn OR
`csvplus.FromFile("sample.csv").Distinct("name", "phone")` Would remove duplicates base on the column fields provided.

**Comment by maxim2266** [comment]
This library is not designed to replace a SQL database, so I can only suggest you to store your data in a database, and from there you can apply queries like `count(*)` or `select distinct`.
